language: java
jdk:
  - openjdk8

script: "mvn cobertura:cobertura -Dmaven.test.skip=true"

branches:
  only:
    - master

notifications:
  email:
    - binarywang@vip.qq.com

after_success:
  - bash <(curl -s https://codecov.io/bash)
